source 'https://github.com/CocoaPods/Specs'
source 'git@github.com:lzackx/zpod.git'

use_frameworks! :linkage => :static

platform :ios, '10.0'


target 'ZAPM_Example' do
  pod 'ZAPM', :subspecs => ['Network'], :path => '../'

  target 'ZAPM_Tests' do
    inherit! :search_paths

    
  end
end
